experiment:
  name: 'grss_pixel_mlp'

device: 0
num_epochs: 40

model:
 name: pixel_mlp
 kwargs:
  hsi_in: 12
  msi_in: 3
  latent_dim: 256
  output_channels: 20
  feature_embedding_dim: 128
  position_embedding_dim: 256
  fe_alg: None
  pe_alg: sinusoidal
  act: 'snake'
  a: 1.0
  input_mode: hsi_msi

dataset:
  name: grss
  kwargs:
    data_dir: './data/GRSS'
    rgb_width: 64
    rgb_height: 64
    hsi_width: 32
    hsi_height: 32
    top_k: 12
    channels:
    gamma: 0.4
    contrast_enhance: True
    conductivity: 0.6341031137853861
    window_size: 3
    split_ratio: 0.8
    data_type: pixel
  batch_size: 256

loss:
  name: focal
  kwargs:
    gamma: 3.0
